# ==========================================================================
# myproject/settings.py  |  Bookshop — file guide
# ==========================================================================
# The configuration centre for the whole project. Nothing here runs on its own -
# Django reads it once at startup and every other file behaves accordingly.
#
# What is switched on, and where it comes from:
#
#   INSTALLED_APPS       corsheaders + Django's built-ins + rest_framework +
#                        drf_spectacular + our own 'pages' app.
#   MIDDLEWARE           CorsMiddleware sits at the top (order matters - it must
#                        run before CommonMiddleware or the CORS headers never
#                        get attached).
#   DATABASES            SQLite, file db.sqlite3 in the project root.
#   TEMPLATES            APP_DIRS=True, so Django finds pages/templates/ on its own.
#   LOGIN_REDIRECT_URL   URL *names* used after login / logout, and the page
#   LOGOUT_REDIRECT_URL  @login_required bounces anonymous users to.
#   LOGIN_URL
#   REST_FRAMEWORK       DRF defaults: every endpoint requires authentication
#                        unless the view overrides it, JWT is the auth method,
#                        drf-spectacular generates the OpenAPI schema.
#   SIMPLE_JWT           Access token 15 min, refresh 7 days, rotate on refresh.
#   SPECTACULAR_SETTINGS Title/description for /api/docs/ + the Bearer auth
#                        scheme so Swagger's "Authorize" button works.
#   CORS_ALLOWED_ORIGINS http://localhost:5173 - the Vite dev server for the
#                        React frontend.
#
# KNOWN ISSUES (see the notes doc):
#   * LOGIN_REDIRECT_URL / LOGOUT_REDIRECT_URL point at the URL name 'book_list',
#     which no longer exists in pages/urls.py -> logging in raises NoReverseMatch.
#   * 'django.middleware.common.CommonMiddleware' is listed twice - harmless,
#     but delete the second one.
#   * SIMPLE_JWT sets BLACKLIST_AFTER_ROTATION = True, but
#     'rest_framework_simplejwt.token_blacklist' is not in INSTALLED_APPS, so
#     old refresh tokens are never actually invalidated.
# ==========================================================================

"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uvsmbvslsxq_*5miz)2hyem+e@0(+j5ik5bew)8^s-f6sfp^*c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',  # Add this
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'drf_spectacular',

    "pages",

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add this at the very top
    'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_REDIRECT_URL = 'book_list'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'book_list'


# settings.py


REST_FRAMEWORK = {
     # Use drf-spectacular for schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',

    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Shorter in production
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # Invalidate old refresh tokens
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # Use a dedicated key in production
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}


# settings.py

SPECTACULAR_SETTINGS = {
    'TITLE': 'Bookshop API',
    'DESCRIPTION': 'API for managing books and authors in our bookshop',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # JWT configuration for Swagger
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
