"""
URL configuration for myproject project.

For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
"""
# ==========================================================================
# myproject/urls.py  |  Bookshop — file guide
# ==========================================================================
# The ROOT URLconf -- the first thing that sees an incoming request. Django
# matches these patterns top to bottom and STOPS AT THE FIRST HIT.
#
#   /admin/                Django admin site (has its own login page)
#   /api/token/            JWT: username + password -> {"access", "refresh"}
#   /api/token/refresh/    refresh token -> a new access token
#   /api/schema/           raw OpenAPI schema, generated by drf-spectacular
#   /api/docs/             Swagger UI -- browse and try the API in a browser
#   /api/redoc/            the same schema, ReDoc styling
#   ''                     everything else -> include('pages.urls'), i.e. the
#                          DRF router at /api/authors/, /api/books/,
#                          /api/reading-list/
#
# NOTE 1 -- 'api/token/' is registered ONCE, with CustomTokenObtainPairView.
# Because Django stops at the first match, adding a stock TokenObtainPairView
# on the same path above it would shadow the custom one and silently drop the
# extra token claims. Don't reintroduce it.
#
# NOTE 2 -- django.contrib.auth.urls (/accounts/login/ etc.) is deliberately
# NOT included. This is a JWT API: clients authenticate at /api/token/, not
# through a session login form. The Django admin has its own separate login,
# so /admin/ is unaffected.
# ==========================================================================

from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)
from rest_framework_simplejwt.views import TokenRefreshView

from pages.views import CustomTokenObtainPairView

urlpatterns = [
    path('admin/', admin.site.urls),

    # JWT authentication
    path('api/token/',         CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(),          name='token_refresh'),

    # API documentation
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/',   SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/',  SpectacularRedocView.as_view(url_name='schema'),   name='redoc'),

    # Our app's router. Listed last: keeping the broadest include at the
    # bottom is the habit that stops future routes being swallowed by it.
    path('', include('pages.urls')),
]
